### ISSUE TITLE
Retranslation button (#*) not working

### ISSUE THREAD

**Issue by pngbill** [adapt-it/adapt-it-mobile#105]
The Retranslation button doesn't appear to be working, and if it isn't already showing, the process of accessing the Retranslation button looses any source text selection that existed at the time the + symbol is pressed to reveal/drop down the list of action buttons (the retranslation icon is the third one down in the drop down list). Later, I figured out that it is possible to have the Retranslation button visible when making a selection of source words to create a Retranslation, but pressing the Retranslation button doesn't allow me to type in a retranslation for the selected words. Instead nothing happens, the selection disappears, and there no phrase box to be seen. I assume that although the #* button is there in the interface you haven't implemented the Retranslation feature yet.

**Comment by adaptitbruce** [comment]
Of course I dunno how selections & retranslations are supposed to work in AIM. In AID, the "selection" is only in a secondary sense a visible highlighting on the screen; the primary thing a selection is in AID is a list of CPile instances which define the scope of the selection, a pointer to the anchor pile (the first pile in the list), and an int for which line of the strip the selection is in (-1 when no selection is current). Then, if the screen's selection isn't visible or is covered or whatever, so long as those things remain, the handlers for things have something they can rely on in all circumstances. --Bruce
  ----- Original Message ----- 
  From: Bill Martin 
  To: adapt-it/adapt-it-mobile 
  Sent: Thursday, September 03, 2015 5:33 AM
  Subject: [adapt-it-mobile] Retranslation button (#*) not working (#105)


  The Retranslation button doesn't appear to be working, and if it isn't already showing, the process of accessing the Retranslation button looses any source text selection that existed at the time the + symbol is pressed to reveal/drop down the list of action buttons (the retranslation icon is the third one down in the drop down list). Later, I figured out that it is possible to have the Retranslation button visible when making a selection of source words to create a Retranslation, but pressing the Retranslation button doesn't allow me to type in a retranslation for the selected words. Instead nothing happens, the selection disappears, and there no phrase box to be seen. I assume that although the #* button is there in the interface you haven't implemented the Retranslation feature yet.

**Comment by eb1** [comment]
Selection cleanup looks like it addressed this issue -- closing.
