### ISSUE TITLE
Import Documents: try importing .txt as USFM if it has markers

### ISSUE THREAD

**Issue by eb1** [adapt-it/adapt-it-mobile#110]
Adapt It Desktop has an option to export USFM as a file with a .txt extension. Currently AIM will treat .txt files as plain text files with no marker processing. It would be nice for AIM to check the .txt file for markers, and if it does appear to have USFM markers, to try and import the file as USFM.

**Comment by pngbill** [comment]
All USFM Scripture files should have an \id BOOKCODE line as the first line in the file. So probably if a file has the \id code marker at or near the beginning of the file you can assume that it will be USFM.

**Comment by adaptitbruce** [comment]
On 11/09/2015 6:46 AM, Erik Brommers wrote:
>
> Adapt It Desktop has an option to export USFM as a file with a .txt
> extension. Currently AIM will treat .txt files as plain text files
> with no marker processing. It would be nice for AIM to check the .txt
> file for markers, and if it does appear to have USFM markers, to try
> and import the file as USFM.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adapt-it/adapt-it-mobile/issues/110>.
>
Yes, indeed! This is one of the most important input options, whether or
not there is a .txt extension. For example, if someone were to copy and
paste USFM marked up plain text, you'd want to process that for markers
too, as AID does, rather than have the markers display for adaptation.

--Bruce

**Comment by eb1** [comment]
AIM now checks for the \id marker in .txt files

- If the file has the \id marker in it, AIM will attempt to import the file as USFM. 
- If the file does not have that marker, AIM will attempt to import the file as plain text.
