### ISSUE TITLE
Adapt screen: need some way to cancel adaptation in the current phrase box

### ISSUE THREAD

**Issue by eb1** [adapt-it/adapt-it-mobile#111]
Currently there doesn't seem to be a way to cancel the edit in the current adaptation edit box using the on-screen keyboard, once that box has been selected. There needs to be some way to do this, so that users can recover from an errant click on the screen.

**Comment by adaptitbruce** [comment]
On 11/09/2015 6:53 AM, Erik Brommers wrote:
>
> Currently there doesn't seem to be a way to cancel the edit in the
> current adaptation edit box using the on-screen keyboard, once that
> box has been selected. There needs to be some way to do this, so that
> users can recover from an errant click on the screen.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adapt-it/adapt-it-mobile/issues/111>.
>
Hi Erik,
What AID does is to have a bool m_bAbandonable  (I think that's what it
is) member on the phrasebox class instance. When the box lands at a new
location, m_bAbandonable is set TRUE. Then, if the phrasebox is moved,
code which does the moving checks that member value - if it is still
TRUE, then the phrasebox contents are thrown away. What makes that
boolean go false in AID, is a) the user clicks in the phrasebox prior to
doing editing; b) he types at least one character, or deletes something
or adds something - any change at all.

If, after doing something that makes m_bAbandonable false he changes his
mind, all he needs do is to clear the phrasebox. AID does not make an
empty KB entry when the box is empty, it will do so only if the user
types the <no adaptation> button on the command bar - that will cause an
empty string to be stored in the KB for that location's source text key.

--Bruce

**Comment by eb1** [comment]
Clicking away from the target field after an errant click into the field will now cancel the edit. This issue can be marked as resolved.
