### ISSUE TITLE
Import documents: support AI collaboration documents

### ISSUE THREAD

**Issue by eb1** [adapt-it/adapt-it-mobile#113]
Currently AIM does checks for duplicate documents by looking for the \id element. This works for whole documents, but not for documents that are in collaboration mode or split out using the Split command. From Bill: 

All files handled as individual chapters by AID (whether via collaboration or that are split into chapters by the Split command in AID), will have undistinguishable \id lines, that is, each of the 28 chapters of Matthew will have the same ID as shown above, \id MAT. In some cases the first chapter will have some additional information if the user put it there when it was a whole book file - information like the revision date and the translators, name, etc.

---
We need to add some extra logic to look for and support these types of files.

**Comment by eb1** [comment]
Some more information for implementing this work item. 

It looks like these files are in .xml format, with the \id item being the same across chapter / other divisions. We can test this so that if the \id is the same, we check to see if the chapter itself has been imported already (looking for the \c tag). If it has, we can reject the file; if not, we can import it with the same bookid given to the other partial file.

This algorithm will work for Collaboration mode documents as well as documents split with the standard chapter marker. I'm not sure how the split "from current point" can be put back together in order; it looks like AI desktop requires the user to specify the document order for rejoining these documents.

**Comment by eb1** [comment]
Spinning off the support for generic "split documents" to issue #119:

The basic algorithm to support AI collaboration mode documents will work for split documents as long as the user retains the chapter marker (\c) as a breaking point. If the user chooses some other point to break the document (AI desktop supports the options "the phrase box location", "A standard format chapter marker (\c)", and "Split into single chapter documents"), the information about how the document is organized is lost. 

AI desktop gets around this by requiring the user to specify the document order for rejoining split documents. AIM would need some similar mechanism to support these kinds of split documents.

**Comment by adaptitbruce** [comment]
Hi Erik, Bill
If AIM is to support document splitting, I suggest it support only (1) at \c, and (2) into single chapter documents. I don't know of anyone who wanted to split a document, and I doubt anyone would find the option "at box location" to be useful. If smaller chunks are wanted, really they should just be chapter-based. If there are no chapters (no USFM), the option should probably be disabled.

--Bruce
  ----- Original Message -----
