### ISSUE TITLE
Cannot switch to different document in same project

### ISSUE THREAD

**Issue by pngbill** [adapt-it/adapt-it-mobile#116]
This stopped me dead in my effort to test the 0.4.0 alpha. After installing 0.4.0 alpha, I had to create a new project which I did with no problems (though it should have preserved my old project through the installation - that's another issue). I then did an import to get a document that I had previously worked on called 01-NYI-MAT09sfm. It opened that file, but there was only one element in the file that got parsed on screen: \id MAT. That was surprising because I can open that same source file in ES File Editor which shows it to have all 38 verses of the input text. 

Now the issue: Since I couldn't test the app with a file that contains only one element, I wanted to open a different document in the same project, but I can't get AIM to open a different document. When I press the < button on the title bar it goes back to the project screen with Project Settings, Import Documents, etc. I can select the Import Documents button and select a different document from the list of documents. However, it keeps displaying 01-NYI-MAT09.sfm document, regardless of what I do. I can click on the Search button, and there I can use the drop down list to select the book name of the file I had imported. But there is no "Go" or "Finish" or "OK" button to complete the selection and get that document loaded. If I then press < to get back to the project settings page, it continues to list the previous 01-NYI-MAT09.sfm file at the bottom. Why can't I switch to a different document in the same project?

**Comment by eb1** [comment]
Some comments:

- App upgrades are being tracked via issue #112. 
- Support for split documents / collaboration mode documents is being tracked via issue #113. For now, please do not use collaboration mode or split documents; the parser cannot deal with them yet. This actually might be the root cause of the issue being reported here.
- Selecting a different document is done through the Search page:

1. From the main / home screen, select Search
2. Either start typing the name of an imported document, or select the document from the drop-down list.
3. In the list of search results, you should either get a list of chapters (for Scripture data) or a single entry (for a text file). Click on an item in the search results list, and it will bring you to the adaptation page for that item.

If no items show up in the list of search results, it's likely that it didn't import the data correctly.

**Comment by pngbill** [comment]
OK, I made some progress, but I'm still a bit confused as to the process of getting books and/or chapters up on screen to adapt. I had imported 3 John using a file named 25-3JN.sfm. Then I clicked on Search which listed "3 Jon" and I selected it. But although it shows in the drop down box, nothing happens. Are you saying that I have to search for something within the file using the edit box that says, "Look up a passage to start adapting"? Why does it not simply load the book once I've selected it? I did manage to get the file I wanted loaded after putting a random character in the edit field until I happened to type a letter that was in the name of the book so that its name would be listed - appearing as "3 Jon 1, No translations (14 total verses)"in a "select a chapter" list. People will have one or more projects, and each project will have a finite number of book files and/or chapter files associated with the particular project. Having to type blindly to find something or get a list of choices to appear is not really intuitive to me, but I'm probably too old school. Is that the way people using mobile devices today locate a discrete file to work on? It would seem more intuitive to me for AIM, once files are imported, and the user selects a book from the drop down list, to simply display a list of all the files or chapters that it knows are associated with that particular book, from which the user can choose. In the case of 3 John, there is generally only a single file with a single (pseudo) chapter, so AIM wouldn't need to provide a chapter list, but could simply load the book file.

**Comment by eb1** [comment]
> OK, I made some progress, but I'm still a bit confused as to the process of getting books and/or chapters up on screen to adapt. I had imported 3 John using a file named 25-3JN.sfm. Then I clicked on Search which listed "3 Jon" and I selected it. But although it shows in the drop down box, nothing happens.

At the point that you select a book in the drop-down list, it should give you the chapter results for that book, similar to the UI in the desktop collaboration dialog (i.e., with the number of translated verses, etc.).

> Are you saying that I have to search for something within the file using the edit box that says, "Look up a passage to start adapting"?

No. You should be able to either use the search box or the drop-down list to get at what you want to translate next.

> Why does it not simply load the book once I've selected it?

I've no idea. It should. Can you forward the file to me and I can take a look? 

> I did manage to get the file I wanted loaded after putting a random character in the edit field until I happened to type a letter that was in the name of the book so that its name would be listed - appearing as "3 Jon 1, No translations (14 total verses)"in a "select a chapter" list. People will have one or more projects, and each project will have a finite number of book files and/or chapter files associated with the particular project. Having to type blindly to find something or get a list of choices to appear is not really intuitive to me, but I'm probably too old school. Is that the way people using mobile devices today locate a discrete file to work on?

Again, there are two ways to do it. If you're more comfortable selecting from a list, great. If you know the name of the book and are comfortable typing until it appears in search results, great. I've tried to accommodate both modes of lookup.

There is a school of thought that drop-down lists are evil on a mobile device (see https://storify.com/lukew/drop-downs-are-the-ui-of-last-resort). I'm not entirely convinced; I do think they have their place.

> It would seem more intuitive to me for AIM, once files are imported, and the user selects a book from the drop down list, to simply display a list of all the files or chapters that it knows are associated with that particular book, from which the user can choose. 

Yes, this is how it should be working now.

> In the case of 3 John, there is generally only a single file with a single (pseudo) chapter, so AIM wouldn't need to provide a chapter list, but could simply load the book file.

There's probably a use case for someone just wanting to see how far along they were on a particular book / chapter. This wouldn't be possible for single-chapter books / non-Scripture books under that type of design. I think I'd rather have the user _always_ need to select the chapter after selecting the book, if only to allow for the "how far am I?" case.

**Comment by pngbill** [comment]
Here is the source text file I was using during the above issue. I had to change the extension from .sfm to .txt for the github file attach mechanism to accept the file. It rejected files with .sfm extension!
[25-3JN.txt](https://github.com/adapt-it/adapt-it-mobile/files/28528/25-3JN.txt)

**Comment by eb1** [comment]
Okay, found the culprit. The usfm parser was picking up an extra return char in the book name; this was in turn causing the drop-down to not find the chapter names for the book. Calling trim() in the usfm parser to remove the extra char fixed the problem; I've also added a trim() call in the search page for files that are already imported, just in case.
