### ISSUE TITLE
Adaptations getting lost on successive openings of document

### ISSUE THREAD

**Issue by pngbill** [adapt-it/adapt-it-mobile#118]
While doing some adapting in 3 John, I interrupted my work on that document several times going back to the project settings page. When I went back into the document, I found that a number of the adaptations that I had done (including a few mergers) were now gone. Some were still there, but others (single word adaptations and mergers) disappeared from the document between the openings of the same document.

**Comment by pngbill** [comment]
This is still a problem. Today after starting afresh (after AIM wiped out my previous project at installation), I noticed that most instances of lost adaptations were for merged phrases.

**Comment by eb1** [comment]
Marking this issue as fixed:

There was a fair amount of rework under the hood for this issue (nothing visible in the UI, however). The main changes were in how the source phrases were stored in the database and referenced in the html:

- In the database, a new column (norder) keeps track of the relative order of items in the chapter being adapted. This allows for inserts of placeholders, as well as merging of phrases and retranslations -- while keeping the order intact if the user leaves the adaptation screen and comes back in later.
- In the html, each pile uses the source phrase ID (database spid column) as a unique identifier -- in the form "pile-<spid>". This allows us to look up each source phrase, as well as to quickly tell if the source phrase is a placeholder, phrase, retranslation or "regular" source phrase.

I've run the changes through the browser, iOS and Android environments to verify the fixes. Acceptance testing should ensure that source phrases persist for placeholder, phrase, retranslation and "regular" text, and that the previous and next functionality is intact.
