### ISSUE TITLE
Android: Tok Pisin unavailable in language settings

### ISSUE THREAD

**Issue by eb1** [adapt-it/adapt-it-mobile#127]
It appears that neither Android nor Chrome include Tok Pisin in their lists of supported languages. We probably need some sort of workaround for these users, so that we can support Tok Pisin in the UI for AIM on Android.

**Comment by eb1** [comment]
Maybe we need to add some sort of general setting like:

Language:
[ ] Use device's language setting
[ ] Use language:  <blah>

Where <blah> is a drop-down list of the locales we support (English, French, Spanish and Tok Pisin at the moment).

**Comment by eb1** [comment]
Created a new page and view (UILanguageView) to allow for overriding the mobile device’s language setting for AIM. This page can be accessed by clicking on the globe icon at the bottom left of the Welcome and home screens, and functions as described in the comments above.

**Comment by KLBradford** [comment]
Hi, Erik. Do you have something (maybe not due right away) that I could start to work on?
