### ISSUE TITLE
Allow selection of source/target languae by ISO 639-2 code

### ISSUE THREAD

**Issue by KLBradford** [adapt-it/adapt-it-mobile#134]
When creating a project, typing an ISO 639-2 code (e.g. "fra") does not select the appropriate language. When I type "fra", I expect to see "french", but that is not selected and doesn't even show in the filtered list.

[tested in brackets/Chrome]

**Comment by adaptitbruce** [comment]
On 22/01/2016 6:47 AM, Erik Brommers wrote:
>
> Closed #134 <https://github.com/adapt-it/adapt-it-mobile/issues/134>
> via 74c9739
> <https://github.com/adapt-it/adapt-it-mobile/commit/74c9739a4b5ea5d5816826c87170d8c4cd9b79c0>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adapt-it/adapt-it-mobile/issues/134#event-522113673>.
>
Hi Erik,  not sure why you are supporting ISO639-2? It's possibly not
helpful. ISO639-3 has the 3 letter codes. ISO639-1 the 2-letter codes
which have to be used in preference to a 3-letter code when a language
has both types of codes. ISO639-2 is just a potential nuisance. It was
superceded by ISO639-3.

--Bruce

**Comment by eb1** [comment]
Sorry, I should have clarified what I did here. This is to support searching for a language by its ISO 639-3 (3-character) codes, not the ISO 639-2 code. AIM will now show language names **and codes** that match the search string.
