### ISSUE TITLE
Exported files on Android are difficult to find

### ISSUE THREAD

**Issue by eb1** [adapt-it/adapt-it-mobile#141]
The document export functionality uses some standard directories given to us by the Cordova file plugin. For iOS, the exported documents can be synched using iTunes Sharing. 

For Android, the Android File Transfer utility (OSX / Windows) can be used to transfer files to a desktop for further processing. However, these exported files are several levels deep in the directory: `Android/data/org.adaptit.adaptitmobile/files`. 

We should investigate this further, to see if there is a better location to save these exported documents.

**Comment by jmarsden** [comment]
On Mon, Feb 8, 2016, at 18:57, Erik Brommers wrote:
> The document export functionality uses some standard directories given
> to us by the Cordova file plugin. For iOS, the exported documents can
> be synched using iTunes Sharing.

> For Android, the Android File Transfer utility (OSX / Windows) can be
> used to transfer files to a desktop for further processing. However,
> these exported files are several levels deep in the directory:
> Android/data/org.adaptit.adaptitmobile/files.

> We should investigate this further, to see if there is a better
> location to save these exported documents.

It might be worth using external storage, and writing to a named
directory (say AdaptItMobile/ ) within that?  If the device has real
removable external storage, cool, they are all set, and can xfer files
that way; if not, they can find the files just one level down from the
top of their virtual "external storage".  Just an idea.

Jonathan
