### ISSUE TITLE
iOS: File Sharing not enabled for Adapt It Mobile

### ISSUE THREAD

**Issue by eb1** [adapt-it/adapt-it-mobile#152]
Adapt It Mobile Version: 0.5.5

Operating System: iOS
OS Version: iOS 9.3.1 
Severity: 2
Description: I just bought an iOS device to test the alpha 6 version of AIM. It looks like there's a separate info.plist item -- UIFileSharingEnabled (with a value of "YES") -- that we need to add for iOS in order to allow File Sharing on the device. Without it, AIM is unable to import documents.

More info here: https://developer.apple.com/library/ios/documentation/Miscellaneous/Conceptual/iPhoneOSTechOverview/CoreServicesLayer/CoreServicesLayer.html#//apple_ref/doc/uid/TP40007898-CH10-SW30

**Comment by GraeCost** [comment]
Hi Erik,

I got that sort of impression from my tests on AIM but I hadn’t figured out what the problem was. Once that permission is enabled in AIM for IOS I should be able to actually import a text file or document.

All the best,

Graeme

**Comment by eb1** [comment]
This actually needs a private build to push out the fix, as the PG build service just pushes out a generic .ipa file. I'll try to get one out tomorrow.
