### ISSUE TITLE
Revert typing / Undo button

### ISSUE THREAD

**Issue by eb1** [adapt-it/adapt-it-mobile#225]
Description: This is related to issue #215:

For this next milestone (0.8.5), we would like to create a simple revert typing / undo button. This would not be a full-blown Undo feature that would allow the user to continue reverting actions to the beginning of the adaptation session (this would require encapsulating the various actions that the user could perform in a Command design pattern -- such a feature could be considered for a future release if there is a need).

Instead, the revert / undo button follows the "dirty" bit for the current edit field. If the user has typed something into the edit field, the button is enabled:

![undo1](https://cloud.githubusercontent.com/assets/1458944/23715188/690ba08a-03f1-11e7-96a1-9c1850840945.png)

They then can click on the Undo button, which will revert the field to its previous state:

![undo2](https://cloud.githubusercontent.com/assets/1458944/23715232/8b997eba-03f1-11e7-9a9d-f7eeb2982e27.png)

Then, when the user clicks on the edit field again, the previous suggested text should appear:

![undo3](https://cloud.githubusercontent.com/assets/1458944/23715299/ba5987f4-03f1-11e7-9102-9f588d809e67.png)

This button should be disabled if there is no currently-focused edit field.

**Comment by adaptitbruce** [comment]
Hi Erik,

Nice. --Bruce

**Comment by eb1** [comment]
Work complete on this item.
