### ISSUE TITLE
App signing for Windows Phone

### ISSUE THREAD

**Issue by eb1** [adapt-it/adapt-it-mobile#27]
It looks like Windows Phone 7.1 / 8 has an app signing and submission process similar to iOS and Android (http://msdn.microsoft.com/library/windowsphone/help/jj206719(v=vs.105).aspx). The PhoneGap build service has a couple fields for entering in a publisher ID and title as well.

This issue it to investigate what needs to be done to have a usable Windows phone version of adapt it mobile.

**Comment by eb1** [comment]
A couple updates on this issue:

1. Windows Phone 7 is no longer supported by cordova; the current options are Windows Phone 8 and Universal Windows Platform (UWP).
2. Selling in the Windows app store requires a developer individual account or organization account. The organization account is ~ $99 USD (one time fee).

I'm not sure how strategic Windows is for AIM presently, so I'm going to push this issue out of the beta release for now and put it in Needs Prioritization.

**Comment by adaptitbruce** [comment]
Yeah, probably not our primary focus. On the other hand, our budget can 
easily handle that expense when one or some of us have feedback from 
some indicating that a Windows Phone or UWP incarnation is going to be 
used by some people if we make it available.

--Bruce

**Comment by eb1** [comment]
Windows app signing steps as of 7/18: http://docs.phonegap.com/phonegap-build/signing/windows/

**Comment by eb1** [comment]
Marking this issue as closed/won't fix. According to a few sites that track mobile device usage, Windows mobile devices have been at <1% of the market share over the last couple years at least. Probably not worth considering.

**Comment by eb1** [comment]
Moving this out of the "Needs prioritization" bucket.
