### ISSUE TITLE
Stop automatic copying of source text into target text (black font)

### ISSUE THREAD

**Issue by mjshowalter** [adapt-it/adapt-it-mobile#300]
Adapt It Mobile Version: Don't know, downloaded 3/17/2018

Operating System: Android

OS Version: Android 7.0

Samsung Galaxy J7 Perx

Severity: 3

Description: Random words were copied directly from the source text into the target text in black font.  It took me a long time to figure out that perhaps I had selected these words accidentally while scrolling or through system error as seen in issue #299.  This is a problem because it resulted in many untranslated words in the knowledge base.

Steps to Reproduce:

1. Randomly select any word in the source text.  It may have been tapped accidentally or through system error as seen in issue #299 
2. Observe system copies source text into target text in black font (I would prefer that it was blank and required typing in)
3. Tap a previous word in the source text to go back to where you were working.
4. Observe that an untranslated word is now unintentionally entered in the knowledge base.

Work-around : User can tap the Undo button before step 3.

Comment: I understand this feature is intended to save the user time when translating between closely-related languages.  However, I found it very annoying when trying to translate from French to English.  I would prefer to type the word in (instead of having it automatically copied) even if it is spelled the same and means the same thing in both languages.  The only case in which I like this feature is copying numerals such as chapter numbers and verse numbers.

Madeleine Showalter

**Comment by eb1** [comment]
Reproduced this issue with the latest milestone. This feature is available in Adapt It under the View menu, but missing from Adapt It Mobile:

![viewmenu](https://user-images.githubusercontent.com/1458944/37751352-9983bfe2-2dc4-11e8-9191-2b432f0a29b5.png)
