### ISSUE TITLE
USX 3.x support

### ISSUE THREAD

**Issue by Berovowilare** [adapt-it/adapt-it-mobile#431]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Berovowilare** [comment]
Hello 

Do you plan to support USX 3.x? With the new possibilities it would by able to add Strong's numbers etc. https://ubsicap.github.io/usx/usx3.0/charstyles.html#w

Thanks

**Comment by eb1** [comment]
Thanks for reporting this issue. Currently Adapt It desktop does support USFM 3.0, and Adapt It Mobile supports  USFM 2.5 and USX version 2.0. It was on my radar to update to USFM and USX 3.x support in Adapt It Mobile as well, but it looks like I never wrote up an issue to track it (yikes!).

**Comment by eb1** [comment]
Marking this work item as closed/ implemented.
