### ISSUE TITLE
Improvements to import document / troubleshooting

### ISSUE THREAD

**Issue by eb1** [adapt-it/adapt-it-mobile#479]
Graeme reported an issue where document import hung while reading / updating the DB, causing some downstream problems when the document was re-imported. 

It would be nice to add some troubleshooting and robustness code to the document import section of the code. Some ideas:

- Adding a timeout value, so that the user isn't stuck on a hung import screen (might need to be adjustable).
- Alternately -- a way for users to cancel the import if it's hanging
- If the import operation fails the timeout / is cancelled, rolling back the import
- Better / more fine-grained status updates when importing (e.g., reporting the number of batches created / returned if possible)

**Comment by GraeCost** [comment]
Hi Erik,

I’m trying to remember other apps where a potentially “hangable” process is running, but haven’t recalled any specific examples.

Would it be possible to have a small window / pane / popover that had a text summary that provided a bit of progress information along with a Cancel button?



The verse number would change as each verse is completed. The user would have a reasonable indication of how long it would take, and would easily see if the import had hung.

Hope this idea helps,

Graeme

**Comment by eb1** [comment]
This is kind of an open-ended issue (yeah, my fault for writing it up that way!). Here's what was done to improve document import:

- Adding a timeout value, so that the user isn't stuck on a hung import screen (might need to be adjustable). 

    **Not done (see next item)**

- Alternately -- a way for users to cancel the import if it's hanging 

    **Done. Added a Cancel button to the import screen**

- If the import operation fails the timeout / is cancelled, rolling back the import 

    **Partially done. The issue here is that the version of SQLite we rely on does not do rollbacks. So if the document has not started importing, no items are added to the database; but if Adapt It Mobile has started adding items to the database, it needs to delete the entire book. This means that merges can be particularly dangerous -- if hung/cancelled, they will delete the old book altogether!**
    
    **This is probably something to revisit in the next release. It might be possible to duplicate the book in the database before the merge attempt: if it fails, AIM uses the saved duplicate; if it succeeds, the saved duplicate can be removed.**

- Better / more fine-grained status updates when importing (e.g., reporting the number of batches created / returned if possible)

  **Done. Adapt It Mobile batches the document in groups of 10,000 source phrases (roughly 10,000 words), so the number of batches will vary from document to document. However, Adapt It Mobile now lists the total batches in the document as well as the number of batches that have completed the import (e.g., "3 of 8 batches completed.")**
