### ISSUE TITLE
First copied project file -- doesn't return to Home Screen

### ISSUE THREAD

**Issue by eb1** [adapt-it/adapt-it-mobile#543]
**Describe the bug**
Found this one post-1.14.0.
When clicking OK on the "import succeeded" dialog after copying the first project file over, the user expects the import screen to go away and the Home Screen to display. Unfortunately, the import screen remains displayed, making the user think that the project file didn't import. The workaround is to click on the back button ("<") at the top of the screen, which will navigate back to the Home Screen, with the project file imported (i.e., it will display the Settings and Import buttons).

**To Reproduce**
1. Launch AIM for the first time, and tap on the Continue button.
2. Tap on Copy Project.
3. Select a project (.aic) file to import. When complete, a screen will tell you the project imported successfully. 
4. Tap on the OK button. 

**Expected behavior**
The Home Screen _should_ display. Instead, the dialog does not go away. The workaround is to tap the back arrow (<) button in the toolbar to return to the Home Screen.

This bug looks like it was introduced with the changes for AIM 1.14.0.

**Comment by GraeCost** [comment]
Hi Erik,

Don’t feel too bad about this little bug — I have experienced similar confusing behaviour with various websites and apps which let you do some action, but keep showing the view about doing the action, leaving me wondering whether the action actually happened or not! For the user, changing what is on the screen to let the user know that the action has happened is important.

All the best,
Graeme
