### ISSUE TITLE
Android: remove READ_EXTERNAL_STORAGE permission

### ISSUE THREAD

**Issue by eb1** [adapt-it/adapt-it-mobile#555]
**Describe the bug**
This is a follow-up to issue #550 .

It looks like the READ_EXTERNAL_STORAGE permission is no longer used in Adapt It Mobile and can also be removed (users can still see and open items on their external storage with the file chooser mechanism that was introduced in AIM 1.14.0). This issue is to track the removal of the permission from Android.

**Comment by IzzySoft** [comment]
Still shows up with today's update btw, so something brings it back in. If you're sure it's not needed, you can try [Removing Unwanted Manifest Permissions With tools:node](https://developermemos.com/posts/removing-unwanted-manifest-permissions/) maybe.

**Comment by eb1** [comment]
@IzzySoft Ugh. Looks like it snuck back in when I updated Android Studio last week. I've re-posted the .apk to the 1.16.0 milestone release, and added a note to myself to recheck this prior to each release, _just in case_... Thanks for catching this!

**Comment by IzzySoft** [comment]
I forward the thanks to my scanner, which reported it to me. (background noise) OK, scanner says I shall keep the glory as it was me who taught it to :man_shrugging: So thanks for keeping up with our reports then! :star_struck:
