### ISSUE TITLE
Remove Android permissions / 3rd party plugin fix

### ISSUE THREAD

**Issue by eb1** [adapt-it/adapt-it-mobile#583]
**Describe the bug**
There is an issue in the 3rd party cordova-plugin-filepath plugin that is requiring the following permissions in order to view / open / import files that are shared with Adapt It Mobile from another device:

For Android versions < 11
- READ_EXTERNAL_STORAGE

For Android versions 11+
- READ_MEDIA_IMAGES
- READ_MEDIA_VIDEO
- READ_MEDIA_AUDIO

For Adapt It Mobile v. 1.16.4, we were able to work around the issue by adding the permissions manually. However, it looks like the plugin is open source and we can make the necessary changes ourself to remove these permissions requests from the plugin.

This issue is to track our removal of the permissions listed above, and the linking in of our personal fork of cordova-plugin-filepath (https://github.com/adapt-it/cordova-plugin-filepath) that contains the permissions fix.

**Comment by mike-hore** [comment]
Hi Erik,

Yes, just letting you know.  All adaptit email for me should now go to ***@***.***

My aapt mail server is going to start charging, so it’s goodbye from me. :-)

Cheers, Mike.



Sent from my iPad
