### ISSUE TITLE
Back button takes you back to the general settings screen

### ISSUE THREAD

**Issue by ZTetriminos** [adapt-it/adapt-it-mobile#598]
Swiping back on any screen will take you back to the general settings screen of the app, instead of the previous screen you were on.

This is particularly annoying when trying to edit the Knowledge Base, as I'm trying to delete a few terms but each time I delete and confirm, swiping back takes me two screens back. I would like to be taken back to the Knowledge Base list..

This issue happens to other menu sections as well.

When I click here or swipe back in this screen...
![ResizedImage_2024-09-11_07-55-25_2267](https://github.com/user-attachments/assets/12e478f7-952c-4674-b2b4-f79d57969fac)

I want to be taken back here...
![Screenshot_20240911-075133](https://github.com/user-attachments/assets/c7ac23aa-8e10-4c9a-9fd2-698e7040dcf7)

...not here! 
![Screenshot_20240911-075226](https://github.com/user-attachments/assets/e2bc5168-f524-4c4f-9fe0-0fe18b18c21e)

**Comment by eb1** [comment]
Hi @ZTetriminos: I was able to find and fix this issue for the next patch release. Should be a couple days. Thanks!
