### ISSUE TITLE
Document Export - AID XML format

### ISSUE THREAD

**Issue by eb1** [adapt-it/adapt-it-mobile#66]
AIM should support the export of documents in Adapt It desktop's XML document format. This would allow users to take the document and keep working in Adapt It desktop.

**Comment by jmarsden** [comment]
i think this could be handled more appropriately as an enhancement
request for AID. Why burden the smaller mobile device with the
conversion work, which could be done on the more capable PC?


In general, lets be careful to avoid feature creep in AIM, and instead
get a minimal version 1.0 released more quickly.


Jonathan
--
Jonathan Marsden jmarsden@fastmail.fm

**Comment by eb1** [comment]
Dev work should be considered completed as of today's checkin. If there are problems discovered, they can be tracked via new issues.
