### ISSUE TITLE
Document Export - USX

### ISSUE THREAD

**Issue by eb1** [adapt-it/adapt-it-mobile#67]
AIM should support the export of documents in USX format. This would allow users to transfer their adapted documents to Paratext for further processing.

**Comment by jmarsden** [comment]
Is this needed for version 1.0? Would saving/export as usfm not work,
followed by conversion on the pc to any desired format? Such tools
probably already exist. Is format conversion on the mobile device truly
required for an initial release? Was it part of the documented AIM
specification?


Jonathan

--
Jonathan Marsden jmarsden@fastmail.fm


On Sat, Apr 11, 2015, at 10:15, Erik Brommers wrote:
> AIM should support the export of documents in USX format. This would
> allow users to transfer their adapted documents to Paratext for
> further processing.


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/adapt-it/adapt-it-mobile/issues/67

**Comment by eb1** [comment]
Export development work should be considered complete with this past checkin. Problems with the USX export can be dealt with via new issues.
