### ISSUE TITLE
Document Export - USFM

### ISSUE THREAD

**Issue by eb1** [adapt-it/adapt-it-mobile#68]
AIM should support the export of documents in USFM format. This would allow users to transfer their adapted text to Bibledit or Paratext for further processing.

Note that USX is actually the preferred format for Paratext these days. This might be a lower-priority work item.

**Comment by jmarsden** [comment]
Can we tag work items with a target release? Maybe this is for
version 2.0?

--
Jonathan Marsden jmarsden@fastmail.fm


On Sat, Apr 11, 2015, at 10:17, Erik Brommers wrote:
> AIM should support the export of documents in USFM format. This would
> allow users to transfer their adapted text to Bibledit or Paratext for
> further processing.


> Note that USX is actually the preferred format for Paratext these
> days. This might be a lower-priority work item.


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/adapt-it/adapt-it-mobile/issues/68

**Comment by adaptitbruce** [comment]
On 12/04/2015 3:17 AM, Erik Brommers wrote:
>
> AIM should support the export of documents in USFM format. This would
> allow users to transfer their adapted text to Bibledit or Paratext for
> further processing.
>
> Note that USX is actually the preferred format for Paratext these
> days. This might be a lower-priority work item.
>
Hi Erik,
That may be true, but our hoped-for main use case will be people who are
not eligible for access to Paratext. I suspect that AIM to AIM transfer
will be common. Key-It is most likely to just produce USFM (but that's
not set in concrete yet). I would think we'd want to suport both USFM
and USX equally.
--Bruce

**Comment by eb1** [comment]
Work item completed for plain text (non-scripture, no tags) and USFM document export:

- For iOS, documents will be saved in the Documents folder for AIM. These can be synched using iTunes Sharing (https://support.apple.com/en-us/HT201301)
- For Android, documents are saved in Internal Storage, in the Android/data/org.adaptit.adaptitmobile/files directory. This directory should be visible using the Android File Transfer utility.

I'll be updating the AIM wiki shortly with instructions on how to perform the export, and then transfer the files to another device.
