### ISSUE TITLE
Weird UI behavior on Search page for Android

### ISSUE THREAD

**Issue by eb1** [adapt-it/adapt-it-mobile#73]
I noticed that the search page doesn't completely display for Android. This is probably due to some weird CSS bug on Android's browser?

Steps to reproduce:

1. Launch AIM
2. Create a project, then import some documents
3. When the documents do finish importing, click on Search from the home page

--> You'll notice that the page opens up way over to the left side of the screen, with maybe 32px of the search field visible. If you click on the search field, it will bring up the on-screen keyboard and recenter the Search page properly.

**Comment by eb1** [comment]
Update on this issue:

I installed the cross-platform [CrossWalk plugin for cordova](https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview), which replaces the normal Android system browser (webview) with the latest Chromium browser. This ensures the latest rendering fixes -- as well as security patches -- are applied to our code.

With Crosswalk installed, the search page renders correctly on a debug build.

I'll leave this issue open until I can verify this on the release build from the PG build site. PG build seems to be having some problems today, so it might be in the next day or so.

**Comment by eb1** [comment]
PhoneGap Build service is now operational. However, the Crosswalk plugin for cordova is not currently supported on PG build, and will not be until PG build supports cordova version 4.x. Here's the reply I got from the PG build staff:
 
> The Crosswalk plugin requires version 4.0.0 or higher. You can enable this as soon as we roll out PhoneGap version 4.x.x and higher on PhoneGap Build.

I'll kick this issue out of Milestone 0.3.0, as it currently depends on a PG build service upgrade.

**Comment by jmarsden** [comment]
Given the differences between building locally and using the build
service, with files in different places etc., do we need some sort of
setup script(s) that prepare a source tree for building (a) locally and
(b) by the build service?  Or is there some other way to automate
handling the changes between the two build environments?

Jonathan
--
Jonathan Marsden
jmarsden@fastmail.fm
 
 
On Tue, Jun 2, 2015, at 08:57, Erik Brommers wrote:
> PhoneGap Build service is now operational. However, the Crosswalk plugin for cordova is not currently supported on PG build, and will not be until PG build supports cordova version 4.x. Here's the reply I got from the PG build staff:


>> The Crosswalk plugin requires version 4.0.0 or higher. You can enable this as soon as we roll out PhoneGap version 4.x.x and higher on PhoneGap Build.


> I'll kick this issue out of Milestone 0.3.0, as it currently depends on a PG build service upgrade.


> —
> Reply to this email directly or view it on GitHub[1]. 

>  
 


Links:

  1. https://github.com/adapt-it/adapt-it-mobile/issues/73#issuecomment-107999459

**Comment by eb1** [comment]
Marking this issue as resolved:

- PhoneGap Build build now supports the crosswalk browser plugin; I've added this plugin to the config.xml file so that our builds now include it for the Android browser.
- With the inclusion of the crosswalk browser, the rendering bug causing this issue no longer occurs on my Lenovo tablet (Android 4.4.2).
- For local builds, Bill found that the "use host GPU" setting needs to be enabled in the emulator for this to work properly. He's added it to the setup script for linux.
