### ISSUE TITLE
Source / Target Languages pages: specifying a language

### ISSUE THREAD

**Issue by eb1** [adapt-it/adapt-it-mobile#99]
From Bill (milestone 0.3.0):

I started the process of Creating a new project. After entering a source language name (Nyindrou), the first few times I clicked on "Next" an alert came up saying "Please enter a language name" [OK]. I somehow managed to get past the source language name alerts, but I'm stuck at the target language name. It seems no matter what I put in the edit box, it thinks the field is empty and the alert keeps popping up "Please enter a language name" [OK]. I tried English and Tok Pisin, but neither get recognized and the alert keeps appearing.

[EB] Currently the Source and Target Languages pages require you to click on a language in the languages list in order to validate the language name properly (this is to avoid misspellings). Unfortunately this does not allow for users to type in the language name themselves without selecting the language from the search results. 

This should be reworked so that the closest language match in the list is suggested to the user -- if they accept this suggestion, AIM will use this language name / code; if they reject this suggestion, AIM should allow them to select the appropriate choice.

**Comment by eb1** [comment]
For this issue, I've modified the validation process for the Source / Target Language name fields:

- If there is something in the edit fields, AIM will look at the languages that match the string entered and suggest the first match -
 "Language found: "<blah>." Use this language?" [Yes] [No]
  If the user clicks Yes, the language name and code are used
  
- If the user clicks No OR if there isn't a match for what the user typed in OR if the user didn't type anything in, AIM tells the user to enter a valid language name and focus returns to the edit field.

**Comment by adaptitbruce** [comment]
Yes, that's also similar to what AID does, so should be easily understood by anyone with an AID background. Nice. --Bruce
  ----- Original Message -----
